version: "3"

services:
  web:
    build: .
    command: sh ./bin/deploy.sh
    environment:
      - EPIKSOUND_FTP_HOSTNAME=$EPIKSOUND_FTP_HOSTNAME
      - EPIKSOUND_FTP_USER=$EPIKSOUND_FTP_USER
      - EPIKSOUND_FTP_PASSWORD=$EPIKSOUND_FTP_PASSWORD
