version: 2
jobs:
  deploy:
    docker: 
      - image: shwanton/circleci

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Build middleman app
          command: docker-compose build

      - deploy:
          name: FTP build to server
          command: docker-compose up

workflows:
  version: 2
  deploy-app:
    jobs:
      - deploy
