version: 2
jobs:
  deploy:
    docker: 
      - image: shwanton/circleci

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Build middleman app
          command: docker-compose -f docker-compose.ci.yml build

      - deploy:
          name: FTP build to server
          command: docker-compose -f docker-compose.ci.yml run app ./bin/setup.sh

workflows:
  version: 2
  deploy-app:
    jobs:
      - deploy
