version: 2
jobs:
  deploy:
    docker: 
      - image: shwanton/circleci

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Build image
          command: docker-compose -f docker-compose.ci.yml build

      - deploy:
          name: Deploy app
          command: docker-compose -f docker-compose.ci.yml up

workflows:
  version: 2
  deploy-app:
    jobs:
      - deploy
